### PR TITLE
Feat/5 upload resume

### LINKED ISSUE #5: Implement UI to upload a resume
### Describe why the project needs this task
Every applicant should be able to upload his resume when applying to a in-house job posting in order to be considered a candidate. Without a UI to upload a resume this is not possible.

### Related user stories
* S10

### Describe the solution to the problem
An applicant will have a UI that lets the select a file (from their computer or from a cloud account).

### PR DESCRIPTION
**Pull request by sulemanmalik**
Closes #5 

i have some unused imports here but leaving them there for now because I want to update it later

### CODE REVIEW

**Comment by erickzhao** [comment]
>i have some unused imports here but leaving them there for now because I want to update it later

@sulemanmalik do you want me to wait until you're done to review it then?

**Review by erickzhao — CHANGES_REQUESTED** [review]
Can we implement the file upload feature before merging this PR?

**Comment by sulemanmalik** [comment]
On it

**Comment by sulemanmalik** [comment]
Closing this PR (had some problems merging on my end will create another one)

**Pull request closed without merging**
